### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by leylaa27** [4ndyZ/JoinMessagePlus#2]
Only those with admin rights can see the join Messages

**Comment by 4ndyZ** [comment]
This plugin doesn't require any permission to see Join/Leave-Message. Maybe there is another plugin which blocks the Join messages.

Do only Join-Messages not work or both Join- and Leave-Messages.

Please provide the following information so that I can help you furthermore.

- Minecraft-Server Version
- Minecraft-Server Flavor (Bukkit or Spigot ...)
- Plugin Version
- Plugin config file
- List of installed plugins (use /plugins)

Thank you very much.
